Repository Pro-Digital-Academy-Frontend-Project/Frontend, pull requests merged in 2024-12, with the labels that each got.

#87 #86 Refactor : 랜딩페이지 종목 클릭 시 페이지 이동
  src/pages/LandingPage/KeywordBox.jsx
Labels: 🔨 Refactor

#88 #66 Feat: main sidebar 구현
  src/App.jsx
  src/components/ChattingBox.jsx
  src/components/ChattingMain.jsx
  src/components/Layout.jsx
  src/components/Sidebar.jsx
  src/pages/ChattingPage/ChattingPage.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/utils/chatContext.jsx
  src/utils/likeContext.jsx
Labels: ✨ Feature

#90 #89 Refactor : 캔들 차트 에러처리 및 랜딩 페이지 기본값 변경
  src/components/ChartBox/CandleChart.jsx
  src/pages/LandingPage/StockBox.jsx
Labels: 🔨 Refactor

#96 #95 Fix : 차트 예외처리
  src/components/ChartBox/CandleChart.jsx
Labels: 🐞 BugFix

#99 #97 Feat : 키워드 페이지 종목에 대한 워드클라우드 추가
  src/components/ChartBox/CandleChart.jsx
  src/components/ChattingMain.jsx
  src/components/SidebarChat.jsx
  src/components/SidebarKeyword.jsx
  src/components/StockWordCloud.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/utils/chatContext.jsx
  src/utils/likeFunction.jsx
Labels: ✨ Feature

#100 Refactor/#85 css
  src/components/Alarm/Alarm.jsx
  src/components/ChattingBox.jsx
  src/components/ChattingInput.jsx
  src/components/Layout.jsx
  src/components/SidebarKeyword.jsx
  src/components/SidebarStock.jsx
  src/pages/LandingPage/StockBox.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/SignUpPage/SignUpPage.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/utils/keywordFunction.jsx
  src/utils/stockFunction.jsx
Labels: 🔨 Refactor

#101 version 0.4.2
  public/img/favi.png
  src/components/Alarm/Alarm.jsx
  src/components/CandleChartSimple.jsx
  src/components/ChartBox/CandleChart.jsx
  src/components/ChartBox/ChartBox.jsx
  src/components/ChartBox/KeywordChartBox.jsx
  src/components/ChattingBox.jsx
  src/components/ChattingInput.jsx
  src/components/ChattingMain.jsx
  src/components/Layout.jsx
  src/components/Sidebar.jsx
  src/components/SidebarChat.jsx
  src/components/SidebarKeyword.jsx
  src/components/SidebarMain.jsx
  src/components/SidebarStock.jsx
  src/components/StockWordCloud.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/StockBox.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/SignUpPage/SignUpPage.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/utils/chatContext.jsx
  src/utils/keywordFunction.jsx
  src/utils/likeFunction.jsx
  src/utils/stockFunction.jsx
  tailwind.config.js
Labels: 🌏 CI/CD

#106 feat(#105): intropage를 '/'로 라우팅 및 다른 라우트 수정, 페이지 구현
  src/components/Header.jsx
  src/components/SearchInput.jsx
  src/components/SearchKeywordInput.jsx
  src/pages/IntroPage.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/StockBox.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/routers/main-router.jsx
Labels: ✨ Feature

#107 #94 Feat: 메인 페이지 뉴스 카드 추가
  package.json
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/NewsBox.jsx
  src/services/newsApi.jsx
Labels: ✨ Feature

#111 Refactor/#109 css refactoring
  src/components/CandleChartSimple.jsx
  src/components/ChartBox/CandleChart.jsx
  src/components/SidebarChat.jsx
  src/components/SidebarKeyword.jsx
  src/components/SidebarMain.jsx
  src/components/SidebarStock.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/StockBox.jsx
Labels: 🔨 Refactor

#113 #108 Refactor : 랜딩 페이지 종목 변경
  src/pages/LandingPage/StockBox.jsx
  src/services/stockApi.jsx
  src/utils/stockFunction.jsx
Labels: 🔨 Refactor

#115 Feat/#112 header search
  src/components/Alarm/Alarm.jsx
  src/components/Header.jsx
  src/components/KeywordSearchModal.jsx
  src/components/SearchInput.jsx
  src/components/SearchKeywordInput.jsx
  src/components/StockSearchModal.jsx
Labels: ✨ Feature

#116 #110 Refactor: news css 수정
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/NewsBox.jsx
Labels: 🔨 Refactor

#119 #114 Refactor : 랜딩 페이지 차트 상단에 종목명 추가
  src/components/ChartBox/ChartBox.jsx
  src/components/SidebarChat.jsx
  src/components/SidebarMain.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/StockBox.jsx
  tailwind.config.js
Labels: 🔨 Refactor

#120 Refactor/#117 ux css
  src/components/Sidebar.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/NewsBox.jsx
  src/pages/LandingPage/StockBox.jsx
  src/utils/stockFunction.jsx
  tailwind.config.js
Labels: 🔨 Refactor

#121 #114 Refactor : 문장 구성 및 CSS 수정
  src/components/ChartBox/UserLike.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/StockBox.jsx
Labels: 🔨 Refactor

#122 Refactor/#117 ux css
  src/components/ChartBox/UserKeywordLike.jsx
  src/components/ChartBox/UserLike.jsx
  src/components/ChattingBox.jsx
  src/components/ChattingMain.jsx
  src/components/Layout.jsx
  src/components/SearchInput.jsx
  src/components/SearchKeywordInput.jsx
  src/components/Sidebar.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/NewsBox.jsx
Labels: 🔨 Refactor

#127 #126 Refactor : 차트 데이터 에러처리 수정
  src/utils/stockFunction.jsx
Labels: 🔨 Refactor

#130 #129 Fix: 채팅 메시지에 대한 시간을 서버에서 생성하도록 수정
  src/components/ChattingInput.jsx
  vite.config.js
Labels: 🐞 BugFix

#131 Version 0.5.2
  src/components/ChattingInput.jsx
  vite.config.js
Labels: 🌏 CI/CD

#132 #129 Fix: 채팅 메시지 시간 재수정
  package.json
  src/components/ChattingInput.jsx
Labels: 🐞 BugFix

#133 Version 0.5.3
  package.json
  src/components/ChattingInput.jsx
Labels: 🌏 CI/CD

#134 #129 Fix: chatting time fix3
  src/components/ChattingBox.jsx
  src/components/ChattingInput.jsx
Labels: 🐞 BugFix

#135 Version 0.5.4
  src/components/ChattingBox.jsx
  src/components/ChattingInput.jsx
Labels: 🌏 CI/CD

#136 #129 Fix: chatting time fix4
  src/components/ChattingBox.jsx
  src/components/ChattingInput.jsx
  src/components/ChattingMain.jsx
  src/components/SidebarMain.jsx
Labels: 🐞 BugFix

#137 Version 0.5.5
  src/components/ChattingBox.jsx
  src/components/ChattingInput.jsx
  src/components/ChattingMain.jsx
  src/components/SidebarMain.jsx
Labels: 🌏 CI/CD

#138 #114 Refactor : CSS 수정
  src/components/Layout.jsx
  src/components/SidebarMain.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/StockBox.jsx
Labels: 🔨 Refactor

#139 Refactor/#117 ux css
  src/App.jsx
  src/components/ChartBox/ChartBox.jsx
  src/components/Header.jsx
  src/components/KeywordSearchModal.jsx
  src/components/Layout.jsx
  src/components/SearchInput.jsx
  src/components/SearchKeywordInput.jsx
  src/components/Sidebar.jsx
  src/components/SidebarKeyword.jsx
  src/components/StockSearchModal.jsx
  src/pages/ChattingPage/ChattingPage.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/StockBox.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/utils/ScrollToTop.jsx
  src/utils/stockFunction.jsx
Labels: 🔨 Refactor

#140 Version 0.5.6
  src/App.jsx
  src/components/ChartBox/ChartBox.jsx
  src/components/Header.jsx
  src/components/KeywordSearchModal.jsx
  src/components/Layout.jsx
  src/components/SearchInput.jsx
  src/components/SearchKeywordInput.jsx
  src/components/Sidebar.jsx
  src/components/SidebarKeyword.jsx
  src/components/SidebarMain.jsx
  src/components/StockSearchModal.jsx
  src/pages/ChattingPage/ChattingPage.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/StockBox.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/utils/ScrollToTop.jsx
  src/utils/stockFunction.jsx
Labels: 🌏 CI/CD

#141 #129 Fix: chatting time fix
  src/components/ChattingBox.jsx
Labels: 🐞 BugFix

#142 Version 0.5.7
  src/components/ChattingBox.jsx
Labels: 🌏 CI/CD

#148 #129 Fix: 메인 사이드바 채팅 메시지 시간 수정
  src/components/ChattingMain.jsx
Labels: 🐞 BugFix

#150 Refactor/#117 ux css
  src/components/CandleChartSimple.jsx
  src/components/ChartBox/CandleChart.jsx
  src/components/Header.jsx
  src/components/SidebarStock.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/StockBox.jsx
Labels: 🔨 Refactor

#152 #151 Docs : Favicon 및 Title 변경
  index.html
Labels: 📃 Docs

#154 Version 0.6.1
  index.html
  public/img/information.png
  src/components/CandleChartSimple.jsx
  src/components/ChartBox/CandleChart.jsx
  src/components/ChattingMain.jsx
  src/components/Header.jsx
  src/components/Instruction.jsx
  src/components/SidebarChat.jsx
  src/components/SidebarStock.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/StockBox.jsx
Labels: 🌏 CI/CD

#155 #153 Fix: 메인 페이지 좋아요 동기화 문제, 미로그인 시 에러처리 수정
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/StockBox.jsx
  src/utils/likeFunction.jsx
Labels: 🐞 BugFix

#159 Version 1.0.0
  src/components/ChattingInput.jsx
  src/components/Layout.jsx
  src/components/SidebarMain.jsx
  src/pages/ChattingPage/ChattingPage.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/NewsBox.jsx
  src/pages/LandingPage/StockBox.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/SignUpPage/SignUpPage.jsx
  src/services/userApi.jsx
  src/utils/likeFunction.jsx
Labels: 🌏 CI/CD

#160 CI/CD : 배포파일 수정
  .github/workflows/deploy.yml
Labels: 🌏 CI/CD
