Repository Pro-Digital-Academy-Frontend-Project/Frontend, pull requests merged in 2024-11, with the labels that each got.

#7 #1 CI/CD : Dockerfile 및 GitHub Actions 설정
  .github/workflows/deploy.yml
  Dockerfile
  nginx.conf
  vite.config.js
Labels: 🌏 CI/CD

#9 #8 Fix : Import Error 해결
  src/App.jsx
  src/main.jsx
Labels: 🐞 BugFix

#17 #15 setting tailwindcss
  .env
  package-lock.json
  package.json
  postcss.config.js
  src/components/Footer.jsx
  src/css/App.css
  src/css/index.css
  src/index.css
  src/main.jsx
  tailwind.config.js
Labels: ⚙ Setting

#20 Feat/#18 feat layout css
  .env
  package.json
  postcss.config.js
  public/img/logo.jpg
  src/components/Chart.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Layout.jsx
  src/components/LayoutKeyword.jsx
  src/components/LayoutStock.jsx
  src/components/SidebarStock.jsx
  src/css/App.css
  src/css/index.css
  src/index.css
  src/main.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/routers/main-router.jsx
  src/services/keywordApi.jsx
  src/services/stockApi.jsx
  tailwind.config.js
Labels: ✨ Feature

#21 Feat/#18,#10 feat layout css
  package.json
  src/components/CandleChart.jsx
  src/components/Chart.jsx
  src/components/Footer.jsx
  src/main.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/services/stockApi.jsx
Labels: ✨ Feature

#22 #14/feat:stock-ranking-page
  package.json
  src/App.jsx
  src/components/CandleChartSimple.jsx
  src/components/Chart.jsx
  src/components/ChartBox/CandleChart.jsx
  src/components/ChartBox/ChartBox.jsx
  src/components/ChartBox/ChartData.jsx
  src/components/Layout.jsx
  src/components/SidebarStock.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/routers/main-router.jsx
  src/services/keywordApi.jsx
  src/services/userApi.jsx
  tailwind.config.js
Labels: ✨ Feature

#23 14 feat stock ranking page
  src/components/ChartBox/CandleChart.jsx
  src/components/ChartBox/ChartBox.jsx
  src/components/Layout.jsx
  src/components/SidebarStock.jsx
Labels: ✨ Feature

#24 Feat#19 키워드 별 종목 랭킹 사이드바
  src/components/Layout.jsx
  src/components/SidebarKeyword.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/routers/main-router.jsx
  src/services/keywordApi.jsx
Labels: ✨ Feature

#26 #19 Feat : 키워드 페이지 즐겨찾기 및 차트 조회
  src/components/SidebarKeyword.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/services/keywordApi.jsx
  src/services/userApi.jsx
Labels: ✨ Feature

#27 14 feat stock ranking page
  src/components/ChartBox/CandleChart.jsx
  src/components/ChartBox/ChartBox.jsx
  src/components/ChartBox/ChartData.jsx
  src/components/ChartBox/UserLike.jsx
  src/components/Layout.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/services/stockApi.jsx
Labels: ✨ Feature

#28 #12 Feat: 소켓 채팅 구현
  lib/api/api.js
  package.json
  src/components/ChattingBox.jsx
  src/components/ChattingInput.jsx
  src/pages/ChattingPage/ChattingPage.jsx
  src/services/chatApi.jsx
Labels: ✨ Feature

#30 #29 Fix : 키워드 즐겨찾기 수정
  src/components/ChartBox/UserLike.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
Labels: 🐞 BugFix

#34 #12 Feat: 채팅 메시지 nickname 보이도록 수정
  package.json
  src/components/ChattingBox.jsx
  src/components/ChattingInput.jsx
  src/pages/ChattingPage/ChattingPage.jsx
Labels: ✨ Feature

#33 #32 feat stock ranking page
  src/components/ChartBox/ChartBox.jsx
  src/components/ChartBox/UserLike.jsx
  src/components/Layout.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/SignUpPage/SignUpPage.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/services/stockApi.jsx
Labels: ✨ Feature, 🔨 Refactor

#36 feat(#35): search CSS 및 기능 구현
  src/pages/StockChartPage/StockChartPage.jsx
Labels: ✨ Feature

#40 Refactor#39
  .env
  .github/workflows/deploy.yml
  src/services/chatApi.jsx
  src/services/keywordApi.jsx
  src/services/stockApi.jsx
  src/services/userApi.jsx
Labels: 🔨 Refactor

#41 Dev
  .github/workflows/deploy.yml
  Dockerfile
  src/components/CandleChartSimple.jsx
  src/components/ChartBox/ChartBox.jsx
  src/components/ChartBox/ChartData.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/services/chatApi.jsx
  src/services/keywordApi.jsx
  src/services/stockApi.jsx
  src/services/userApi.jsx
Labels: 🌏 CI/CD

#42 Refactor/#37 stock chart component
  src/components/CandleChartSimple.jsx
  src/components/ChartBox/ChartBox.jsx
  src/components/LikeButton.jsx
  src/components/SearchInput.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/StockBox.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/utils/likeFunction.jsx
  src/utils/stockFunction.jsx
Labels: 🔨 Refactor

#47 Feat/#43 landing page
  index.html
  package.json
  src/components/CandleChartSimple.jsx
  src/components/ChartBox/CandleChart.jsx
  src/components/ChattingInput.jsx
  src/components/Header.jsx
  src/components/Layout.jsx
  src/components/SearchInput.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/StockBox.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  tailwind.config.js
Labels: ✨ Feature

#49 #31 Refactor : 키워드 페이지 차트 추가
  src/pages/KeywordChartPage/KeywordChartPage.jsx
Labels: 🔨 Refactor

#52 #5 Feat: chat UI
  eslint.config.js
  package.json
  src/App.jsx
  src/components/Chatting/ChattingRoom.jsx
  src/components/ChattingBox.jsx
  src/components/ChattingInput.jsx
  src/components/Layout.jsx
  src/components/SidebarChat.jsx
  src/pages/ChattingPage/ChattingPage.jsx
  src/utils/chatContext.jsx
  tailwind.config.js
Labels: ✨ Feature

#53 Refactor/#48 css
  src/components/Layout.jsx
  src/pages/LandingPage/StockBox.jsx
Labels: 🔨 Refactor

#55 #54 Fix: 사이드바 동작 방식 수정
  src/components/Layout.jsx
Labels: 🐞 BugFix

#56 #50 Refactor : 키워드 페이지 CSS 조정
  src/components/ChartBox/KeywordChartBox.jsx
  src/components/ChartBox/UserKeywordLike.jsx
  src/components/SearchKeywordInput.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/utils/keywordFunction.jsx
  src/utils/likeFunction.jsx
Labels: 🔨 Refactor

#57 Refactor/#48 css
  src/components/CandleChartSimple.jsx
  src/components/Layout.jsx
  src/components/SidebarStock.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/StockBox.jsx
Labels: 🔨 Refactor

#58 #50 Refactor : 키워드 차트 페이지 CSS 수정
  src/components/ChartBox/UserKeywordLike.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
Labels: 🔨 Refactor

#62 #60 Feat: 채팅방 목록 api 연결
  src/components/SidebarChat.jsx
  src/services/chatApi.jsx
Labels: ✨ Feature

#65 #64 Feat: chat icon UI
  .prettierrc.cjs
  src/components/ChattingBox.jsx
  src/components/ChattingMain.jsx
  src/components/Sidebar.jsx
Labels: ✨ Feature

#67 Feat/#63 wordcloud
  package.json
  src/components/ChartBox/ChartBox.jsx
  src/components/ChartBox/ChartData.jsx
  src/components/ChartBox/UserKeywordLike.jsx
  src/components/ChartBox/UserLike.jsx
  src/components/Footer.jsx
  src/components/Layout.jsx
  src/components/WordCloud.jsx
  src/pages/LandingPage/StockBox.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/SignUpPage/SignUpPage.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/utils/keywordFunction.jsx
Labels: ✨ Feature

#68 #61 Feat : 키워드 랜딩 페이지
  src/components/SearchKeywordInput.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/services/keywordApi.jsx
Labels: ✨ Feature

#71 feat(#70): keywordApi에 즐겨찾기 랭킹 api 추가 및 sidestockbar에서 api 호출
  src/components/SidebarStock.jsx
  src/services/keywordApi.jsx
Labels: ✨ Feature

#73 #69 Feat : 랜딩 페이지 사이드바 (종목)
  src/components/SidebarKeyword.jsx
  src/services/stockApi.jsx
Labels: ✨ Feature

#75 #74 Refcator : 키워드 페이지 CSS 수정
  src/components/SearchKeywordInput.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
Labels: 🔨 Refactor

#78 version 0.3.1
  .prettierignore
  .prettierrc.cjs
  index.html
  package.json
  public/stockey_logo.svg
  src/components/Alarm/Alarm.css
  src/components/Alarm/Alarm.jsx
  src/components/ChartBox/ChartBox.jsx
  src/components/ChartBox/ChartData.jsx
  src/components/ChartBox/UserKeywordLike.jsx
  src/components/ChartBox/UserLike.jsx
  src/components/ChattingBox.jsx
  src/components/ChattingMain.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Layout.jsx
  src/components/SearchKeywordInput.jsx
  src/components/Sidebar.jsx
  src/components/SidebarChat.jsx
  src/components/SidebarKeyword.jsx
  src/components/SidebarStock.jsx
  src/components/WordCloud.jsx
  src/pages/KeywordChartPage/KeywordChartPage.jsx
  src/pages/LandingPage/KeywordBox.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/StockBox.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/SignUpPage/SignUpPage.jsx
  src/pages/StockChartPage/StockChartPage.jsx
  src/services/chatApi.jsx
  src/services/keywordApi.jsx
  src/services/stockApi.jsx
  src/services/userApi.jsx
  src/utils/keywordFunction.jsx
Labels: 🌏 CI/CD

#79 Feat/#77 routing
  src/components/SidebarStock.jsx
  src/pages/LandingPage/StockBox.jsx
Labels: ✨ Feature

#83 #82 Refactor : 채팅 연결 URL 수정
  src/pages/ChattingPage/ChattingPage.jsx
Labels: 🔨 Refactor
